wireguard-install.sh

without resolvconf package, systemd unit file will fail in Debian 10 and ubuntu 18.04 or higher versions
see error below 
```
Oct 17 12:11:39 Asus-VivoBook wg-quick[25620]: [#] ip link add wg0 type wireguard
Oct 17 12:11:39 Asus-VivoBook wg-quick[25620]: [#] wg setconf wg0 /dev/fd/63
Oct 17 12:11:39 Asus-VivoBook wg-quick[25620]: [#] ip -4 address add 10.9.0.3/24 dev wg0
Oct 17 12:11:39 Asus-VivoBook wg-quick[25620]: [#] ip link set mtu 1420 up dev wg0
Oct 17 12:11:39 Asus-VivoBook wg-quick[25620]: [#] resolvconf -a wg0 -m 0 -x
Oct 17 12:11:39 Asus-VivoBook wg-quick[25620]: /usr/bin/wg-quick: line 31: resolvconf: command not found
Oct 17 12:11:39 Asus-VivoBook wg-quick[25620]: [#] ip link delete dev wg0
Oct 17 12:11:39 Asus-VivoBook systemd[1]: wg-quick@wg0.service: Main process exited …
```

added missing package - resolvconf

---

wireguard-install.sh

Added extended Fedora support:
* Use native Wireguard in Fedora >= 32
* Use firewalld configuration
Solves and simplifies https://github.com/angristan/wireguard-install/issues/54

Use native WireGuard in Fedora >= 32 + support firewalld

---

wireguard-install.sh

Current port `1194` conflicts with OpenVPN listening port.
Wireguard docs use port `51820` so we'll use that.
Fix #63.

Change Wireguard port from OpenVPN default

---

wireguard-install.sh

This commit puts the client creation logic into a function.
By running the script followed by `add_client`, the user will be asked a few questions and a new peer will be added.
Removing client is **not** supported.
The client files have random names.
Fix for https://github.com/angristan/wireguard-install/issues/3

Add support for adding more clients

---

wireguard-install.sh

Generate a unique pre-shared key for each client as per the WireGuard protocol to improve post-quantum resistance.
1. https://www.wireguard.com/papers/wireguard.pdf#subsection.5.2
2. https://wiki.archlinux.org/index.php/WireGuard#Key_generation
3. https://doc.turris.cz/doc/en/public/wireguard

Generate unique pre-shared key for each client

---

README.md
wireguard-install.sh

I followed the style of the openvpn-install repository and used some of its code. Thanks to everyone that [contributed](https://github.com/angristan/openvpn-install/blame/master/openvpn-install.sh) there.
The other additions are:
- cleaned some minor code
- use IPv6 if IPv4 isn't available
- add input validations, fixes #86 . The regex rules I used **need improvements**
- assign secondary DNS to primary DNS value if it's empty. I know #75 was already open for this so I added @chrislewicki as co-author. If this isn't OK for someone, I can remove the commit. Fixes #68 
- use `$SERVER_WG_IPV4` and `$SERVER_WG_IPV6` when suggesting the client IP
- save user DNS to `params` file and apply it to all clients, removing support for customizing DNS for individual clients. If this is a problem we …

Refactor script

---

README.md
wireguard-install.sh

Ubuntu: remove PPA, use native packages

---

wireguard-install.sh

If linux-lts is installed then the suitable headers are in linux-lts-headers package.

Arch LTS-kernel

---

wireguard-install.sh

If the FORWARD chain policy defaults to DENY, it must explicitly allow traffic from the external to the wg interface.
To solve this, the patch just adds
iptables -A FORWARD -i ${SERVER_PUB_NIC} -o ${SERVER_WG_NIC} -j ACCEPT;

Add forwarding eth0 -> wg0

---

wireguard-install.sh

Linux interface names seem to be limited to 15 characters, as referenced [here (IFNAMSIZ)](https://www.gnu.org/software/libc/manual/html_node/Interface-Naming.html) and [in the kernel](https://elixir.bootlin.com/linux/v5.6/source/include/uapi/linux/if.h#L33). So, 16 minus "its terminating zero byte"
This becomes an issue once you want to use `wg-quick` with a `CONFIG_NAME` longer than 15 chars. You will receive this error:
```bash
$ wg-quick up conf-too-long-cant-you-see.conf
$ wg-quick: The config file must be a valid interface name, followed by .conf
```
This PR forbids `CLIENT_NAME`s longer than 15 characters. 
Tested on ubuntu 20.04.
Cheers!

Forbid client names exceeding 15 chars in length

---

wireguard-install.sh

- Since September 2020, AdGuard public DNS servers have moved to new
address. See here - https://adguard.com/en/blog/adguard-dns-new-addresses.html

Update AdGuard default public DNS addresses

---

wireguard-install.sh

On Arch Linux, already installed packages are reinstalled during the initial setup. The `--needed` flag skips packages that are already installed and up-to-date.

Fix unnecessary reinstall of packages

---

wireguard-install.sh

Fix #189
Using `sudo` as root, `SUDO_USER` will be set to `root`

Fix HOME_DIR check

---

wireguard-install.sh

I have removed 3 packages for Arch Linux installation because:
- Linux headers are not needed for building WireGuard kernel module, it is already included on the kernel.
- "iptables" is a required dependency of "base" package which is installed on every Arch Linux installation.

Remove unneeded packages on Arch Linux

---

wireguard-install.sh

Restarting the service leads connected clients to lose some packets

 Add hot reloading

---

wireguard-install.sh

This PR fixes https://github.com/angristan/wireguard-install/issues/263
Since Raspbian and Debian share OS version ID in /etc/os-release, and there are the same wireguard packages in both distros, it's OK to consider them the same OS further down in the script.

Fix installation on Raspbian systems

---

wireguard-install.sh

close Remove default value "n" when uninstalling #369
The character "n" is no longer in the prompt but it is still the default value.

remove default char "n" from uninstall step

---

README.md
wireguard-install.sh

added support for AlmaLinux.
Without this changes, it uses 'centos' but check for version 7 fails.
yum has been replaced by dnf.

AlmaLinux support added

---

wireguard-install.sh

Fixes https://github.com/angristan/wireguard-install/issues/321

Fixing firewall for Oracle cloud VMs

---

README.md
wireguard-install.sh

Tested on Aws ec2 with alpine v3.21
#205

Add Alpine Linux support
